name: ecommerce-infra

services:
  dozzle:
    image: amir20/dozzle:v10
    container_name: dozzle
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    external: true
